let intro = [
    "ALL YOU CAN EAT",
    "19 Restoran All You Can Eat di Jakarta yang Perlu Banget Kamu Coba",
    "14 November 2022",
    "Bagi sebagian besar orang yang termasuk dalam golongan kuat makan, memesan makanan di restoran all you can eat merupakan pilihan yang paling menguntungkan. Konsep all you can eat mengharuskan kamu membayar makanan satu kali saja untuk dapat menikmati semua makanan all you can eat tersebut.    <br>    <br>Biasanya di restoran all you can eat terdapat berbagai menu mulai dari makanan pembuka, makanan utama, hingga hidangan penutup berupa aneka dessert. Menemukan restoran all you can eat di Jakarta juga tidaklah sulit lho.    <br>      <br>Ada banyak sekali restoran yang menerapkan konsep seperti ini di Jakarta mulai dari yang menyajikan menu shabu-shabu, BBQ, sushi, hingga steak. Wow, membayangkannya saja sudah mampu membuat perut kamu bergejolak ya? Nah, buat kamu yang porsi makannya banyak, kamu harus simak rekomendasi restoran all you can eat di Jakarta berikut ini ya! Pasti tidak akan menyesal deh!     <br>  <br>  1. Gyu Kaku    <br>Neo Soho Mall, Lantai Lower Ground    <br>Jl. Letjen S. Parman, Slipi, Jakarta Barat    <br>Di atas Rp 200,000/orang    <br>    <br>Review oleh Riani Rin    <br>    <br>Super yummy all you can eat.    <br>Disini paketnya ada yg standard buffet, ataun premium buffet. kl gue ambil yg standar, ada 9 pilihan menu daging dan banyak lagi menu lainnya. Kayak seafood, goreng2an, side dish, appetizer, dessert, bener2 bikin kita jadi kalap kalau makan disini.    <br>Kualitas daging disini itu mantul banget! bener bener good quality. sebanding dengan harga yang dibanderol 238k+ dan 281k nett nya.    <br>Ini bisa banget jadi tempat untuk bikin acara dengan rekan, keluarga, atau teman2    <br>Recommended place!</p>    </div><img id='fotofnb' src='./img/fnb/topic1.jpg' alt='' />",
    "<div class='isi'>  <div class='artikel'>  <p id='textfnb2'>2. Collage - Hotel Pullman Central  <br>  <br>Hotel Pullman Central Park, Lantai L  <br>Jl. Letjen S. Parman, Slipi, Jakarta Barat  <br>Di atas Rp 200,000/orang  <br>Review oleh Jessica Sisy @jessica_sisy @jktculinarydiary  <br>  <br>IFTAR RAMADHAN DINNER  <br>  <br>Having dinner here and mostly the menu is Middle East food during Ramadhan Season. Di sini cukup lengkap mulai dari appetizer ada aneka salad dan ada soup. Main course adalah Indonesian, Japanese, Middle East, Korean, Chinese, and Indian food, menurut gua yg middle east makanannya cukup berempah. ada nasi Mandhi dan Lamb Kebuli yang dibuat lgsg sama cooker disana. Makannya hangat, masih fresh! enak loh! takjilnya beragam ada Umali ini enak banget! ada kolak, bubur ketan hitam, kurma, dan gorengan  <br>Main course ada fresh made pasta, kebab, aneka nasi dan lauk, mie baso, steak, dsb.  <br>Pilihannya banyak ya. Dessert juga ada choco fondue sama cakes. Umalinya must try! Ada es krim dan sorbet juga  <br>Harganya Rp 588k++/pax tp tenang aja ada promo kartu kredit up to 50% dan untuk All member San Accor Plus member, Selamat mencoba!  <br>  <br>3. Sake+  <br>  <br>Plaza Senayan Arcadi, Lantai 1  <br>Jl. New Delhi Pintu 1 Senayan, Senayan, Jakarta Selatan  <br>Di atas Rp 200,000/orang  <br>  <br>Review oleh Rebecca Rouli Samaria  <br>  <br>SERASA MAKAN DI JEPANG!  <br>Makanan dan tempatnya bener-bener serasa lagi di Jepang! Mulai dari dekorasi dan ambiencenya hingga pelayanannya sangat ramah.  <br>Makanannya juga enak dan bikin pengen kembali lagi. Pas banget makan nabe dan rame hangat dilengkapi dengan 2 free sake (tsunade dan seppuku) dari pergikuliner yang rasanya seger dan ngenakin!  <br>  <br>4. Tucano's Churrascaria  <br>  <br>Senayan City, Lantai Lower Ground  <br>Jl. Asia Afrika, Senayan, Jakarta Selatan  <br>Di atas Rp 200,000/orang  <br>  <br>Review oleh Kharismanisa @kharis.nurul  <br>B AJA~  <br>  <br>Penasaran karena kata orang2 enak tapi menurutku B aja.  <br>Dagingnya beberapa oke, empuk, less effort untuk mengunyah. Picanha and cupim I give 8/10. Sisanaya 7/10.  <br>Untuk harga 330rb, ku prefer ke all u can eat Jepang. So sorry.  <br>But ini tempatnya enak. Sepi dari keramaian mall karena tempatnya di ujung. Side dishnya juga enak2  <br>Kalau mau coba silahkan...</p>  <br>",
];

let artikel1 = [
    "ALL YOU CAN EAT",
    "Restoran All You Can Eat di Gading Serpong yang Ramah di Dompet",
    "Larasati Ayeshaputri | 30 Juli 2019",
    "Dijamin kenyang tanpa jadi bangkrut. Ingin traktir makan teman-teman di ulang tahunmu? Atau mungkin kamu sedang suntuk dengan pekerjaan atau kampus, dan ingin makan enak? Biasanya keinginan seperti ini dihalangi oleh bujet, terutama untuk yang tinggal di kost. Tapi, berbahagialah kalau kamu tinggal di Karawaci, karena ada beberapa restoran all you can eat di Gading Serpong yang semuanya sangat wallet friendly alias ramah dompet! <img src='../img/fnb/topic%201.jpg'> <br>",
    "Buat kamu yang ingin makan enak meski bujet terbatas, nih, bisa mampir ke beberapa rekomendasi AYCE di Gading Serpong berikut ini!<br> 1. Onokabe<br> <br>Kalau ditilik dari namanya, Onokabe All You Can Eat Suki and Grill, terlihat seperti restoran all you can eat di Gading Serpong pada umumnya yang bertema kuliner khas Asia Timur.Padahal, Onokabe juga menyediakan makanan Italia, Indonesia, dan Korea.Di Onokabe kamu diberikan waktu 120 menit untuk mencoba suki, pasta, kambing guling, dan lain-lainnya. Restoran ini menjadi pilihan pas untuk kamu yang ingin makan bareng keluarga atau teman-teman yang punya selera yang berbeda-beda.<br> <br>Pastikan kamu booking dulu sebelum datang ke Onokabe karena restoran ini sering ramai.<br> <br>Harga: Rp105.000-Rp200.000 per orang<br> <br>2. Kushiya Monogatari<br><br>Kalau tempat all you can eat yang satu ini cukup unik, karena ini adalah tempat di mana kamu bisa menggoreng banyak tusuk-tusukan sesuka kamu. Berlokasi di AEON BSD, setiap meja di Kushiya dilengkapi dengan deep fryer yang ditetapkan di suhu 170 derajat Celcius agar makanan kamu dapat tergoreng sempurna.<br> <br>Tak hanya menyediakan daging dan sayur dalam tusukan, kamu juga bisa memilih varian menu lain seperti miso soup, nasi kari, spring roll, kaarage, kroket, sampai chocolate fondue.<br> <br>Harga: Rp100.000-Rp200.000 per orang </p> <br>"
];

let artikel2 = [
    "ALL YOU CAN EAT",
    "3 Restoran Sushi All You Can Eat yang Lagi Hits di Jakarta",
    "Triq Purnamasari | 12 Januari 2023",
    "Lagi bosan sama menu All You Can Eat (AYCE) yang isinya daging melulu? Eits, tenang! Belakangan ini kan mulai banyak hadir pilihan AYCE yang nggak biasa alias antimainstream, loh. Mulai dari sushi, dimsum, ramen, toppoki, penyetan hingga seblak. Tinggal dipilih deh menu apa yang sedang ingin kamu nikmati, baik seorang diri ataupun bersama keluarga dan sahabat. Nah, sesuai request dari beberapa SobiPegi, kali ini Pegipegi mau merekomendasikan deretan restoran sushi enak, favorit, dan memang lagi hits yang bisa dinikmati sepuasnya di Jakarta. Buat kamu yang juga ikutan penasaran, bisa cek nama restorannya di bawah ini, ya!<br>  <img src='../img/fnb/sushi.jpg'>",
    "<br>1.THREE WISE MONKEYS<br><br>Berlokasi di Jalan Senopati No. 46, Kebayoran Baru, Jakarta Selatan, 3 Wise Monkey menyajikan konsep AYCE dengan menu tradisional khas Jepang. Beberapa menu andalannya yaitu salmon sashimi, salmon lava, beef cheese roll, 3 wise monkey special roll, dan aburi salmon belly with truffle sauce. Selama di sini, kamu juga akan dimanjakan dengan suasana modern dan perpaduan tradisional Jepang yang nyaman banget.<br><br>HARGA: SEKITAR RP305.000* PER ORANG (INCLUDE SERVICE AND TAX), SELAMA 90 MENIT<br><br>2. SECRET SUSHI<br><br>Yang satu ini, sempat viral di akhir tahun 2022 lalu! Berlokasi di East Coast, Pantai Indah Kapuk, Jakarta Utara, Secret Sushi hadir dengan desain interior Instagramable. Untuk menunya sendiri mirip dengan restoran Okinawa berada dalam satu group yang sama. Selain gyu truffle ramen, kanikama salad, dan beef enoki yang endeus banget, kamu juga bisa menikmati agemono alias aneka gorengan ala Jepang.<br> <br>HARGA: SEKITAR RP300 RIBU* PER ORANG, SELAMA 90 MENIT<br><br>3. NO NA MA<br> <br>Mau makan sushi enak sepuasnya di tempat yang fancy? Ke NO NA MA Restaurant, yuk! Bertempat di hotel Le Meridien, Jalan Jend. Sudirman, Jakarta Pusat, restoran mewah harga ramah satu ini menawarkan suasana yang nyaman bergaya Jepang dengan deretan ruang privat beralaskan tatami (tikar Jepang). Menu andalan yang wajib kamu coba yaitu sushi dan sashimi segar yang diimpor langsung dari Jepang. Oh ya, sebelum ke sini, kamu harus reserved dulu, ya!<br><br>HARGA: SEKITAR RP250.000* PER ORANG, SELAMA 90 MENIT"
];

let artikel3 = [
    "FOOD AND BEVERAGE",
    "Cafe Instagrammable di Tangerang dengan Arena Outdoor untuk Bersantai",
    "Lydia Kristiani | 24 Desember 2020",
    "Merasa suntuk? Kekurangan inspirasi saat bekerja? Itu artinya kamu butuh mencari waktu sesaat untuk bersantai di tempat yang asyik. Salah satu pilihan yang mudah adalah dengan mengunjungi cafe yang memiliki desain menarik. Tidak hanya interior, kini semakin marak cafe Instagrammable dengan area outdoor yang sama kerennya, termasuk di Kota Tangerang.. Ingin mencoba? Simak dulu rekomendasi TripZilla di bawah ini untuk referensimu sebelum menjelajahi Tangerang!  <img src='../img/fnb/dessert.jpg'>",
    "1. Hirup udara kaya oksigen di Kebun Ide<br><br>Baru melihat foto-fotonya saja sudah membuat mata segar. Bagaimana tidak, cafe Instagrammable di Tangerang ini punya area outdoor yang rimbun dan menghijau dengan aneka tumbuhan yang terawat. Kamu bahkan bisa duduk leyeh-leyeh di tamannya karena disediakan tikar atau main bulutangkis dengan menyewa raket dan kok. Ada pula kebun hidroponik dan area di dalam ruang yang tetap bernuansa alam<br> <br>Menu unggulan di Kebun Ide adalah gelato dengan beragam rasa seperti matcha, speculaas, buah naga atau kale yoghurt. Unik, kan? Makanan dan minuman yang ada di sini disajikan dengan sederhana namun menarik untuk dinikmati<br> <br>2. Pilih kursi atau bean bag di Ol Pops Coffee<br> <br>Coba bayangkan kamu membaca buku favorit di salah satu bean bag yang berwarna cerah. Atau duduk bekerja di laptopmu di salah satu meja dengan hiasan tanaman yang imut ini. Nyaman banget, kan? Mau datang sendirian atau bersama teman, sama serunya di OI Pops Coffee. Bahkan area dalam cafenya pun terlihat teduh dan tenang<br> <br>Kamu dapat memesan berbagai menu semisal bubur ayam, nasi dengan aneka lauk atau sandwich di sini. Pilih sudut yang kamu inginkan dan sambil menikmati angin sepoi-sepoi, makanan yang kamu santap juga akan terasa lebih nikmat lho<br> <br>3. Desain yang ikonik di Red Door Koffie House & Bistro<br> <br>Sesuai namanya, kamu akan melihat pintu merah besar di Red Door Koffie House & Bistro ini. Area dalam ruangnya akan membuatmu betah dan ingin selfie terus. Tapi jangan lupa naik ke area rooftop ya! Sebab di cafe Instagrammable ini kamu bisa nongkrong cantik sambil melihat pemandangan sekitar Tangerang. Kalau melihat dari sisi ini ditambah cuaca yang cerah, dijamin akan terasa lebih berkesan<br> <br>Menu di cafe ini sangat bervariasi mulai dari masakan Indonesia hingga mancanegara. Cobalah sop buntut atau bakso cabe ijo. Jika ingin mengecap rasa yang berbeda, kamu bisa memesan seporsi grilled lobster dan ditutup dengan beberapa buah macaron yang cantik ini<br> <br>4. Kumulo Creative Compound yang sarat kreativitas<br> <br>Berjalan-jalan di Kumulo Creative Compound akan membuat penatmu hilang. Deretan bangunan berbentuk asimetris ini sukses mengundang kekaguman banyak orang dengan warna dan penempatannya yang indah dipandang. Jika berkunjung pada pagi atau sore hari, kawasan ini terasa nyaman dan membuat harimu terasa lebih rileks<br>"
];
export {intro,artikel1,artikel2,artikel3}