let artikel1 = [
    "Daftar Harga HP Samsung Terbaru 2023: Galaxy A Series",
    "../img/foto 1.jpeg",
    "Jumat, 14 April 2023 | 13:59 WIB Penulis: Prihastomo Wahyu Widodo",
    "KONTAN.CO.ID - JAKARTA. Untuk Anda yang mencari HP murah, daftar harga HP Samsung berikut ini wajib disimak. Jika Anda mencari HP kelas menengah terbaik di pasaran, deretan produk Samsung Galaxy A Series berikut ini juga bisa jadi piliihan. Daftar harga HP Samsung terbaru dari Galaxy A Series tentu sangat ramah untuk Anda yang memiliki budget terbatas. Anda bisa dengan mudah menemukan produk dengan harga Rp 1 jutaan atau Rp 2 jutaan. Saat ini pun Samsung Galaxy A Series sudah kedatangan nama baru, mereka adalah Galaxy A34 5G dan Galaxy A54 5G. Keduanya bisa jadi pilihan terbaik untuk Anda yang mencari produk kelas menengah. <br/> <br/> Samsung Galaxy A34 5G hadir dengan prosesor MediaTek Dimensity 1080, RAM 8GB, kamera utama 48MP, serta baterai 5.000 mAh dengan fast charging 25W. Di Indonesia, harga HP Samsung A34 5G dibanderol mulai dari Rp 4.999.000 sampai Rp 5.399.000 saja. <br /> <br /> Di level berikutnya, ada Samsung Galaxy A54 5G yang bisa Anda pilih dalam daftar harga HP Samsung terbaru berikut ini. HP Samsung terbaru 2023 ini bekerja dengan prosesor Exynos 1380, RAM 8GB, kamera utama 50MP, serta baterai 5.000 mAh dengan fast charging 25W. Secara resmi harga HP Samsung A54 5G ada di kisaran Rp 5.999.000 sampai Rp 6.399.000. HP Samsung terbaru lain yang lahir di tahun 2023 adalah Samsung Galaxy A14 Series. Model pertama adalah Samsung A14 4G yang hadir dengan prosesor Helio G80, RAM hingga 6GB, kamera utama 50MP, serta baterai berkapasitas 5.000 mAh. Harga HP Samsung A14 4G untuk varian terbaiknya hanya Rp 2.699.000."
  ];

let artikel2 = [
  "10 Game FPS Terbaik di Android",
  "https://thumb.vdvc.id/vivagadget/1265x711/2023/03/06/6405b0fc2de63-call-of-duty-mobile_gadget.jpg",
  "Senin, 6 Maret 2023 | 16:28 WIB oleh: Ali Imran",
  "Gadget – Saat ini, android bukan hanya digunakan untuk berkomunikasi dan browsing internet saja. Namun, sudah banyak orang yang menggunakan android untuk memainkan game. Game android sendiri sudah semakin berkembang dan memiliki kualitas yang semakin baik dari waktu ke waktu. Oleh karena itu, dalam artikel ini kami akan membahas beberapa game terbaik untuk android yang patut dicoba. Berikut ini adalah beberapa game tembak-tembakan terbaik yang tersedia di perangkat Android. Game-game ini menawarkan pengalaman menembak yang seru dan memacu adrenalin dengan kualitas grafis yang memukau dan gameplay yang menantang.Berikut ini adalah beberapa game tembak-tembakan terbaik yang tersedia di perangkat Android. Game-game ini menawarkan pengalaman menembak yang seru dan memacu adrenalin dengan kualitas grafis yang memukau dan gameplay yang menantang. Berikut ini adalah beberapa game FPS terbaik di Android Call of Duty: Mobile adalah game tembak-tembakan yang sangat populer dan menawarkan grafis yang indah serta gameplay yang seru dan intens.Game ini memiliki berbagai mode game, termasuk mode multiplayer dan battle royale, serta banyak pilihan senjata yang dapat dipilih. PlayerUnknown's Battlegrounds (PUBG) Mobile adalah game battle royale yang sangat populer. Game ini menawarkan grafis yang memukau dan gameplay yang menantang di mana pemain harus bertahan hidup hingga menjadi satu-satunya yang tersisa di pulau terpencil. <br/><br/> Shadowgun Legends adalah game tembak-tembakan sci-fi yang menawarkan grafis yang memukau dan gameplay yang seru dan menantang. Game ini memiliki mode game berbagai macam, termasuk mode multiplayer dan campaign mode. N.O.V.A. Legacy adalah game tembak-tembakan sci-fi yang menawarkan grafis yang memukau dan gameplay yang seru dan menantang. Game ini memiliki mode game berbagai macam, termasuk mode multiplayer dan campaign mode, serta berbagai senjata dan kemampuan yang dapat ditingkatkan.<br/><br/> Critical Ops adalah game tembak-tembakan yang menawarkan grafis yang bagus dan gameplay yang seru dan menantang. Game ini menawarkan mode game berbagai macam, termasuk mode multiplayer dan deathmatch, serta banyak pilihan senjata dan opsi kustomisasi. Modern Combat 5: eSports FPS adalah game tembak-tembakan yang menawarkan grafis yang memukau dan gameplay yang seru dan menantang. Game ini memiliki mode game berbagai macam, termasuk mode multiplayer dan single player campaign mode, serta banyak senjata dan kemampuan yang dapat ditingkatkan."
];
let artikel3 = [
  "Dua HP Gahar OnePlus Ini Dapat Sertifikat TKDN",
  "../img/gambarartikelgadget2.jpeg",
  "Anggoro Suryo - detikInet || 29 Apr 2023 19:45 WIB",
  "Dari pantauan detikINET di laman Peningkatan Penggunaan Produk Dalam Negeri (P3DN) milik Kemenperin,dua HP tersebut punya kode CPH2449 dan CPH2493,Sertifikatnya didaftarkan oleh PT. Bright Mobile Telecommunication dan masing-masing punya nilai TKDN sebesar 35,95% dan 36,65%.CPH2449 ini dipastikan adalah OnePlus 11 5G sementara CPH2493 ini belum bisa dipastikan serinya, namun kemungkinan besar adalah OnePlus Nord 3 yang belum dirilis.Sebelumnya diberitakan, tanda-tanda kembalinya OnePlus ke Indonesia sudah ada sejak akhir Februari lalu, dan kini akhirnya mereka memastikan kehadirannya kembali di Indonesia.Bocoran spesifikasi ini berasal dari Yogesh Brar, yang juga membocorkan kisaran harga OnePlus Nord 3 untuk pasar India. Menurutnya, Nord 3 akan mengusung layar 6,7 inch 1240 x 2772 pixel dengan panel AMOLED dan refresh rate 120Hz.Kamera utamanya akan menggunakan sensor 64 MP dan kamera ultrawide 8 MP serta kamera macro 2 MP. Spesifikasi ini identik dengan OnePlus Ace 2V yang diluncurkan di China pada awal April ini. Dari sini bisa diasumsikan kalau Nord 3 adalah versi rebranding dari Ace 2V.Dari pantauan detikINET di laman Peningkatan Penggunaan Produk Dalam Negeri (P3DN) milik Kemenperin,dua HP tersebut punya kode CPH2449 dan CPH2493,Sertifikatnya didaftarkan oleh PT. Bright Mobile Telecommunication dan masing-masing punya nilai TKDN sebesar 35,95% dan 36,65%.CPH2449 ini dipastikan adalah OnePlus 11 5G sementara CPH2493 ini belum bisa dipastikan serinya, namun kemungkinan besar adalah OnePlus Nord 3 yang belum dirilis.Sebelumnya diberitakan, tanda-tanda kembalinya OnePlus ke Indonesia sudah ada sejak akhir Februari lalu, dan kini akhirnya mereka memastikan kehadirannya kembali di Indonesia.Bocoran spesifikasi ini berasal dari Yogesh Brar, yang juga membocorkan kisaran harga OnePlus Nord 3 untuk pasar India. Menurutnya, Nord 3 akan mengusung layar 6,7 inch 1240 x 2772 pixel dengan panel AMOLED dan refresh rate 120Hz.Kamera utamanya akan menggunakan sensor 64 MP dan kamera ultrawide 8 MP serta kamera macro 2 MP. Spesifikasi ini identik dengan OnePlus Ace 2V yang diluncurkan di China pada awal April ini. Dari sini bisa diasumsikan kalau Nord 3 adalah versi rebranding dari Ace 2V."
];
let artikel4 = [
  "Duh, HP Redmi Note 12 Pro Terbakar di Saku Pengguna",
  "https://akcdn.detik.net.id/community/media/visual/2023/04/30/redmi-note-12-pro_169.jpeg?w=700&q=90",
  "Adi Fida Rahman - detikInet",
  "Redmi Note 12 Pro belum lama diluncurkan secara global, namun HP garapan Xiaomi ini sudah tersandung kabar tidak mengenakan. Handphone tersebut dilaporkan terbakar di saku pengguna di India. Dia kemudian merasakan sensasi terbakar dan mendapati HP sudah mulai terbakar.  <br/><br/> Naveen seketika melemparkan perangkat tersebut ke tanah agar api tak mengenai kulitnya. Belum jelas apa yang memicu kebakaran sebab saat itu HP tersebut tidak sedang diisi ulang. Redmi Note 12 Pro milik Naveen hancur total terbakar api. Saya buru-buru mengambil ponsel saya dari saku dan meletakkannya di tanah agar tidak terbakar. Terima kasih Tuhan, tidak ada luka di tubuh saya. Namun, ponsel itu benar-benar hancur. Saat kejadian telepon tidak digunakan,Dari sini bisa diasumsikan kalau Nord 3 adalah versi rebranding dari Ace 2V.Dari pantauan detikINET di laman Peningkatan Penggunaan Produk Dalam Negeri (P3DN) milik Kemenperin,dua HP tersebut punya kode CPH2449 dan CPH2493,Sertifikatnya didaftarkan oleh PT. Bright Mobile Telecommunication dan masing-masing punya nilai TKDN sebesar 35,95% dan 36,65%.CPH2449 ini dipastikan adalah OnePlus 11 5G sementara CPH2493 ini belum bisa dipastikan serinya, namun kemungkinan besar adalah OnePlus Nord 3 yang belum dirilis.Sebelumnya diberitakan, tanda-tanda kembalinya OnePlus ke Indonesia sudah ada sejak akhir Februari lalu, dan kini akhirnya mereka memastikan kehadirannya kembali di Indonesia.Bocoran spesifikasi ini berasal dari Yogesh Brar, yang juga membocorkan kisaran harga OnePlus Nord 3 untuk pasar India. Menurutnya, Nord 3 akan mengusung layar 6,7 inch 1240 x 2772 pixel dengan panel AMOLED dan refresh rate 120Hz.Kamera utamanya akan menggunakan sensor 64 MP dan kamera ultrawide 8 MP serta kamera macro 2 MP. Spesifikasi ini identik dengan OnePlus Ace 2V yang diluncurkan di China pada awal April ini. Dari sini bisa diasumsikan kalau Nord 3 adalah versi rebranding dari Ace 2V." 
];
let artikel5 = [
  "Review Galaxy A54 5G: HP Samsung Terbaik di Kelas Menengah",
  "https://akcdn.detik.net.id/community/media/visual/2023/03/15/samsung-galaxy-a54-13_169.jpeg?w=700&q=90",
  "Adi Fida Rahman - detikInet || Kamis, 13 Apr 2023 07:45 WIB",
  "Jakarta - Galaxy A54 5G menjadi salah satu HP Samsung yang ditunggu kehadirannya tahun ini. Sebab para pendahulunya punya kisah sukses di pasaran. Ponsel tersebut menawarkan spesifikasi dan fitur menarik namun dibanderol dengan harga masih ramah kantong. Karena itu begitu kabar Galaxy A54 5G sampai di telinga detikINET pun semangat menanti kedatangannya.Dan begitu Galaxy A54 resmi dirilis detikINET langsung menguji kemampuannya. Hasilnya begitu memuaskan, bahkan kemampuannya jauh lebih baik dari Galaxy A53 yang dirilis tahun lalu"
];
export {artikel1,artikel2,artikel3,artikel4,artikel5}